import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Header } from '../components/header'
import { Footer } from '../components/footer'

const sans = Montserrat({
	subsets: ["latin"],
	variable: "--font-montserrat",
	weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: 'Characters in StarWars',
  description: 'Generated by The Force',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='min-h-screen'>
      <head>
        <link rel='icon' href='/favicon.ico'/>
      </head>
      <body className={`bg-gradient-to-b from-[#16141c] to-[#2c1c54] ${sans.variable} font-sans font-normal text-xs`}>
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  )
}